#!/bin/sh
#
# Store and restore time from the hardware clock.
# If available, run chronyd as well.

start() {
    hwclock -sv
    if command -v chronyd >/dev/null 2>&1 && ! pidof chronyd >/dev/null; then
        chronyd
    fi
}

stop() {
    if ! pidof chronyd >dev/null; then
        hwclock -wv
    fi
}
