#!/bin/sh

# Find the first non-loopback interface
CARD="$(ip -br link show | cut -d\  -f1 | grep -v lo | head -n1)"

# CARD="enp63s0" # or hardcode your own

start() {
    ip link set up "$CARD"
    dhcpcd &
}

stop() {
    ip link set down "$CARD"
    killall dhcpcd || pkill dhcpcd
}
