#!/bin/sh

# Start agetty on tty2, respawning it as needed

start() {
    while :; do
        openvt -w -f -c 2 -- sh -c 'exec agetty tty2'
        sleep 0.1
    done &
}

# TODO: ->
stop() {
    exit 0
}
