#!/bin/sh

# Start agetty on tty4, respawning it as needed

start() {
    while :; do
        openvt -w -f -c 4 -- sh -c 'exec agetty tty4'
        sleep 2
    done &
}

# TODO: ->
stop() {
    exit 0
}
