#!/bin/sh

. /etc/sin/lib

export TERM=linux
export PATH="/usr/bin:/usr/sbin"
export HALT="${0##*/}"
echo "$HALT" > /halt

# Banner

clear
printf " ===================================\n"
printf " \033[1;34m*\033[0m Sin v|VERSION| initiating %s \033[1;34m*\033[0m\n" "$HALT"
printf " ===================================\n\n"

# Send SIGTERM to /sbin/init to initiate halt sequence

kill 1
